=== olfa90/aid-id-pry-09-es-redsoc/trunk/data_store/schemas/question_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="question">
        <xs:all>
            <xs:element name="identifier" type="xs:positiveInteger"/>
            <xs:element name="topic" type="xs:string"/>
            <xs:element name="text" type="xs:string"/>
            <xs:element name="type" type="listaTipos"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="answer">
        <xs:all>
            <xs:element name="code" type="xs:positiveInteger"/>
            <xs:element name="text" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="listaTipos">
        <xs:restriction base="xs:string">
            <xs:enumeration value="single"/>
            <xs:enumeration value="multiple"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="qdescriptor">
        <xs:complexType>
            <xs:all>
                <xs:element name="question" type="question"/>
                <xs:element name="proposal">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="answer" type="answer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="selected">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="answer" type="answer"/>
                            <xs:element name="comment" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== olfa90/aid-id-pry-09-es-redsoc/trunk/data_store/answers/eduardo.perrino@gmail.com/1_eu_1263231389164.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:qdescriptor xmlns:ns1="preferencesAgent.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="preferencesAgent.com file:/C:/Users/eduardo.perrino/Documents/Redes%20sociales%20moviles/question_schema.xsd">  
    <question>
        <identifier>1</identifier>
        <topic>destinations</topic>
        <text>Â¿Te gusta viajar a londres?</text>
    </question>
    <proposal>
        <answer>
            <code>1</code>
            <text>si</text>
        </answer>
        <answer>
            <code>2</code>
            <text>no</text>
        </answer>
    </proposal>
<selected><answer><code>1</code><text>Texto de prueba</text></answer><comment>Comentario de prueba</comment></selected></ns1:qdescriptor>

=== olfa90/aid-id-pry-09-es-redsoc/trunk/service-provider/src/main/webapp/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<qdescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/workspace/semanthic-app/service-provider/src/main/webapp/schemas/question_schema.xsd">
    <question>
        <identifier>50</identifier>
        <topic>topic0</topic>
        <text>text0</text>
        <type>single</type>
    </question>
    <proposal>
        <answer>
            <code>50</code>
            <text>text1</text>
        </answer>
        <answer>
            <code>50</code>
            <text>text2</text>
        </answer>
    </proposal>
</qdescriptor>

=== olfa90/aid-id-pry-09-es-redsoc/trunk/data_store/questions/3/3_eu.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:qdescriptor xmlns:ns1="preferencesAgent.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="preferencesAgent.com file:/C:/Users/eduardo.perrino/Documents/Redes%20sociales%20moviles/question_schema.xsd">  
    <question>
        <identifier>2</identifier>
        <topic>destinations</topic>
        <text>Gustatzen zaizu Miami joatera?</text>
    </question>
    <proposal>
        <answer>
            <code>1</code>
            <text>si</text>
        </answer>
        <answer>
            <code>2</code>
            <text>no</text>
        </answer>
    </proposal>
</ns1:qdescriptor>
